### ISSUE TITLE
Obelisk\integrated\fworld pctCortex is not decrementing 

### ISSUE THREAD

**Issue by wumpusman** [Astera-org/obelisk#112]
Only uses heuristic, this looks like an issue when code was transferred from emery.

**Comment by rcoreilly** [comment]
note: currently using a 5 epoch step for increasing pct, and this works well for 512 trial epochs.

**Comment by wumpusman** [comment]
kk, since our fworld is over the network, I'll pass that as an action along with epoch, and other info.

**Comment by wumpusman** [comment]
Fixed, about to push, BUT what is the trial size, and epoch number (512 trials per N epochs, or 512 epochs where each one has N trials)?
Also, what's the minimum number of epochs and trial number where you observe reasonable performance atm.

> note: currently using a 5 epoch step for increasing pct, and this works well for 512 trial epochs.

**Comment by wumpusman** [comment]
Ah I see, it's currently 200 x 200
