### ISSUE TITLE
Add more tasks to ci

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#121]
1. run tests
2. lint checks
3. static checks
4. code coverage
5. anything else?

**Comment by garymm** [comment]
1. Tests run.
2. We have formatting for Go and Python. Adding for Bazel in https://github.com/Astera-org/obelisk/pull/301. I'll work on adding for C++.
3. Static checks for go are in https://github.com/Astera-org/obelisk/pull/294. Probably enough for now.
4. Code coverage seems useless until we actually start prioritizing writing tests.

So I'll leave this open until we have formatting for C++.
