### ISSUE TITLE
Fworld sizing issue on windows

### ISSUE THREAD

**Issue by wumpusman** [Astera-org/obelisk#13]
By default on windows 11, the GUI on FWorld seems to be extremely zoomed in. Not sure if this is due to a recent change, or if this also applies to Linux versions.

@rcoreilly - i'm more assigning this to you, so I can talk to you about this. I didn't observe this behavior a day ago on my mac.

**Comment by rcoreilly** [comment]
all good?

**Comment by wumpusman** [comment]
issue resolved 👍
