### ISSUE TITLE
Jobczar hangs if running in the background

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#172]
If you try running it with something like

`go run . &`

It seems to freeze for some reason. This might be a problem when running on an actual server.
Also the input listener receives an empty string which probably signifies being disconnected from stdin.
Likely all infra services have the same behavior.

**Comment by jedmccaleb** [comment]
It is not meant to be run tis way. I run it under screen

**Comment by etuleu** [comment]
Ah ok. I did some research because I was curious why it happens and found this: https://unix.stackexchange.com/questions/25024/why-do-backgrounded-processes-sometimes-stop-spontaneously

I think it can easily be fixed by ignoring that signal. I'd like to be able to run in background locally so I can test all processes without needing screen.

With the signal handler we can also kill the entire process when receiving ctrl+c which currently doesn't work.
