### ISSUE TITLE
Jobboard loses the production/localhost state when you switch tabs

### ISSUE THREAD

**Issue by jedmccaleb** [Astera-org/obelisk#184]
Looks like it also reloads all the .js files for some reason.

**Comment by etuleu** [comment]
That is weird. It works fine on firefox linux. It even maintains local/prod state across refreshes.
Which browser are you on? I haven't tested on anything other than firefox yet.

**Comment by etuleu** [comment]
Just tested Chrome on linux also seems fine.

**Comment by etuleu** [comment]
Michael just tested Firefox and Edge on Windows and seemed fine too ...

**Comment by jedmccaleb** [comment]
Do you get the .js being reloaded? Maybe just fix that and my issue will go away

**Comment by etuleu** [comment]
No, nothing changes for us.

**Comment by etuleu** [comment]
Is it possible you have a file watcher that does it? Like VSCode has some weird stuff.

**Comment by etuleu** [comment]
Are you using vscode live server?
