### ISSUE TITLE
Job status is still working if the binary fetching fails

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#192]
To reproduce put in the wrong port for binserver in the worker config or bring down binserver. The binary download will fail but the job status will not be updated, so it will forever remain in the working state.

Solution:
Probably just need to handle this error and update the job as failed.

**Comment by jedmccaleb** [comment]
This is the worker downloading from the binserver? I think it should do exponential backoff like it does when it can't contact the jobczar. maybe we need to give it a notifyAuthorities like ODPW has

**Comment by etuleu** [comment]
It does do backoff but it never sets the job as failed, so it looks like it is working on it forever. I don't think this will be very common but it happened to me because I had the port number wrong in config. I will try a fix.

**Comment by etuleu** [comment]
Oh you're right the downloading part does not have backoff. I see what you mean now.
