### ISSUE TITLE
Rearrange the way the world and model talk to each other

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#203]
We want the world to be the server (thrift wise), but we also want the world to control the stepping.

Why do we want this?

We want the world to be server so it can start first and then wait for the agent (or multiple in the future) to connect to it.

We want the world to control stepping in order to support multiple agents in the same world.

**Comment by rcoreilly** [comment]
would it be possible to have a switch?  when developing the models, it is very important to be able to interactively step.  Alternatively, we could have the direct go interface handle the developing and testing functions, and use the server for "production" testing of already-developed models.  We can discuss more today perhaps.

**Comment by etuleu** [comment]
Sorry @rcoreilly just saw this! Yes that would definitely be useful to have. Just to clarify you mean the ability to use the same agent + model but in the same process as you would normally do?
