### ISSUE TITLE
Cleanup agent code

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#27]
1. Move agent dir from emergent to here
2. Deprecate worlds and models repos in favor of this one
3. Update references to the deprecated repos (we are currently still referencing them)
4. Same for c++ code in egan (it is referencing thrift  lib from worlds repo in the makefile)
5. Update interface to not expose network types (keep them contained)
6. Some of these might be done already but double check

**Comment by rcoreilly** [comment]
just remove from emergent once moved -- keep it clean! :)
