### ISSUE TITLE
make protobrain work with simple egan

### ISSUE THREAD

**Issue by jedmccaleb** [Astera-org/obelisk#288]
1. networking - done
2. matching inputs to the model layers - half way done, needs more double checking and testing

**Comment by garymm** [comment]
Notes:
We need to do these TODOs:
https://github.com/Astera-org/obelisk/blob/20b293867b150322a513ece119b193c5e5506fa3/models/integrated/egan_protobrain/egan.go#L205

Erdal suggests reading protobrain-FWorld to get inspiration.

GetAllObservations() maps from input layer name to a tensor input.

We need to handle vestibular and inters and ask randy about the other stuff.

We should write a unit test for this function.

We should add checking for this code:
https://github.com/Astera-org/obelisk/blob/20b293867b150322a513ece119b193c5e5506fa3/models/agent/helpers.go#L95

Want to check that if passed in too few inputs (make sure all layers have inputs)
Want to check that if passed in too many inputs (some input doesn't correspond to a layer)

I'll start with vestibular.

**Comment by garymm** [comment]
Notes from discussion with Andrew on what he's doing wtih OpenAI Gym / Python:
* Every 100 steps it creates a new world.
* We should check in an egan.cfg file that we can share.
* Reward calculation is in worlds/pyegan/env.py `step()`. But this doesn't need to be the same between different models. I should ask Randy what he wants the reward signal to be.

**Comment by garymm** [comment]
# Notes from discussion with Randy

## What representation should the model receive?

* Use emergent/patgen.PermutedBinaryMinDiff to generate patterns for each color that are far apart from each other in Hamming distance. Look at ra25 in emer/emergent for an example.
* Any visually distinct entity should get its own pattern. So the squares with little other colors on them should have their own patterns

## What is popcode doing?

For anything that’s a real valued number like depth, we need to have a representation that has sufficient resolution. Discriminating the different spiking rates of neurons is not something that other neurons can do. Neurons are tuned to a certain input. They fire in a gaussian way with the mean at the preference. So the input is a scalar like a distance and the output is a tensor of spiking rates of how different neurons respond to that scalar.

**Comment by garymm** [comment]
Current status:
* Egan changes in https://github.com/Astera-org/egan/tree/garymm/instinct-agent
* Protobrain changes in https://github.com/Astera-org/obelisk/tree/garymm/protobrain-egan

They run together but protobrain doesn't seem to learn.
I tried running protobrain + FWorld for comparison but that doesn't seem to be working.
Will work on it with Erdal and Randy tomorrow.

**Comment by garymm** [comment]
It seems to be running. Will look at it more with Randy on Monday.
