### ISSUE TITLE
connect egan to OpenAI baselines implementations

### ISSUE THREAD

**Issue by thangduong** [Astera-org/obelisk#312]
1- add reset to egan
2- PyEgan
3- EganGym(Egan)
   - deal with step blocking and passing data

**Comment by jedmccaleb** [comment]
What do you need reset to do?

**Comment by thangduong** [comment]
reset to some fresh initial state.  some of the rl agents train by running the environment over and over.

**Comment by jedmccaleb** [comment]
hmm we can already set the number of steps for a particular world and the number of worlds in the training set.  Does the agent need to short circuit this? Just seems like this should be controlled by the training setup which you can already specify.

**Comment by thangduong** [comment]
what happens if the agent dies before the N number of steps set?  does it automatically reset?
In OpenAI's model, the agent side controls the environment in the training process.  it calls Step(.) to move forward, Reset(.) to restart.

**Comment by jedmccaleb** [comment]
If the agent dies the world is reset and it keeps going for the remaining steps

**Comment by thangduong** [comment]
does it exit when it's done with the N number of steps?  this is not exactly like a lot of the open ai environments, so we'll have to play with what would make sense.  maybe if we just have a reset in c++ to restart from step 0 somehow, then we can play with the python code on exactly how this woud fit into open ai's framework.  this reset can reset the world to some random state?

**Comment by jedmccaleb** [comment]
lets discuss when I'm there later
