### ISSUE TITLE
JobCzar Reconnect to DB if the connection breaks

### ISSUE THREAD

**Issue by jedmccaleb** [Astera-org/obelisk#32]

**Comment by etuleu** [comment]
I tested this and it seems that it does reconnect on every request.

Steps I took to test:

1. bring down mysql using: service mysql stop
2. refresh jobboard to make sure it is down; I see an error printed that says: 
07-12 16:24:19, Error: dial tcp 127.0.0.1:3306: connect: connection refused
3. bring mysql back up using: service mysql start
4. refresh jobboard and see it loading properly

So I think the mysql library we are using is doing it right.
