### ISSUE TITLE
Implement multiarm bandit world

### ISSUE THREAD

**Issue by wumpusman** [Astera-org/obelisk#45]
Pain and Pleasure as additional features.

**Comment by wumpusman** [comment]
write it in go.

**Comment by rcoreilly** [comment]
CollinsFrank14 is key paper showing advantages of go vs. nogo pathways in bg in relation to rl models -- I *think* they have a simple bandit-level task testing this..

**Comment by rcoreilly** [comment]
desiderata: make it available locally in one directory for easy running / testing.
