### ISSUE TITLE
ra25 crashes when clicking on pats file in Vulkan

### ISSUE THREAD

**Issue by wumpusman** [Astera-org/obelisk#47]

**Comment by rcoreilly** [comment]
@wumpusman give it a try! bug took a good long while to track down, bug finally found it -- timing issue for windows with more complex rendering that takes longer..

**Comment by rcoreilly** [comment]
grr.. I updated my windows machine and just saw that the Pats bug is not fixed :(  I was using another similar case in gogi that reliably crashed, but unfortunately the fix doesn't seem to go far enough for Pats.. will investigate further tomorrow.

**Comment by rcoreilly** [comment]
Just pushed further update that actually fixes this bug..  https://github.com/Astera-org/obelisk/pull/48
