### ISSUE TITLE
remove separate world and models repo

### ISSUE THREAD

**Issue by wumpusman** [Astera-org/obelisk#60]
world and models exist in obelisk, just adds confusion.

**Comment by jedmccaleb** [comment]
you mean remove: https://github.com/Astera-org/models and https://github.com/Astera-org/worlds ?

**Comment by jedmccaleb** [comment]
I deleted worlds. Models still has a bunch of issues lmk if there is anything there you want to port over before I delete it also

**Comment by wumpusman** [comment]
yeah I meant those repos. On my end there isn't anything. I'll post to
obelisk to see if Randy and or Andrew want to at least copy the issues or a
particular branch.
